# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 38a1b5390428afcaa7f074ac023d07457055a012c9232d715ab5405ba0896dd83878ea61d8e03226a5e3a74528d7063a7ea90307576c859fc8fdbb1357d44c1e

test:
  secret_key_base: 308497ca2f9637df97a9e5589c1f288dcf601749f0871abcff9fb1c95e9934129f0ee8c8b41aaaf872d7a331a176a49f1ec12d2cb395a2c3d5b37d6d1037da6f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
